[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[functions]
  node_bundler = "esbuild"

[functions.generate-image]
  included_files = []
  external_node_modules = ["form-data", "node-fetch"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  # Environment variables are set in Netlify dashboard
  # Required environment variables:
  # - OPENAI_API_KEY: Your OpenAI API key (set in Netlify dashboard)

[context.deploy-preview.environment]
  # Environment variables are set in Netlify dashboard
  # Required environment variables:
  # - OPENAI_API_KEY: Your OpenAI API key (set in Netlify dashboard)